[hyprland]
config = "'hypr' 'kitty' 'btop' 'fastfetch' 'swayimg' 'swaync' 'sys64' 'waybar' 'wlogout' 'wofi' 'xdg-desktop-portal'"

[nvim]
packages = "'neovim' 'git' 'python-pynvim' 'tree-sitter-cli'"
config = "'nvim'"
local = "''"

[scripts]
local = "'bin'"

